Split reporting dag
palladiumkenya/airflow-deployment pull request #8
Opened 2023-11-22 09:31 UTC by cbrianbet

Split linelist and aggregates into different Dags

2023-11-23 08:04 UTC, nthusi-codes requested changes

2023-11-23 08:04 UTC, nthusi-codes commented on production/dags/reporting_aggregates_tables_etl_dag.py
> +load_aggregate_txcurr >> load_aggregate_tx_new_hts_cascade  >> load_aggregate_vl_outcome_and_uptake >> load_aggregate_otz_eligibility_and_enrollments >> load_aggregate_otz_outcome >> load_aggregate_o
Just a note. When moving on to a new line in the dag task routes, the last task in the line should also be the first task in the next line. i.e 
....... >> load_a_task >> load_b_task
load_b_task >> load_c_task ........

2023-11-24 05:53 UTC, cbrianbet commented on production/dags/reporting_aggregates_tables_etl_dag.py
> +load_aggregate_txcurr >> load_aggregate_tx_new_hts_cascade  >> load_aggregate_vl_outcome_and_uptake >> load_aggregate_otz_eligibility_and_enrollments >> load_aggregate_otz_outcome >> load_aggregate_o
Hey @nthusi-codes I see that this is the way I have written the code 
ie last task on line 121 is the first on line 122 and so on

2023-11-24 05:53 UTC, cbrianbet commented on production/dags/reporting_tables_etl_dag.py
> +load_linelist_FACTART >> load_linelist_FACTART_Palantir >> load_linelist_vl_non_suppressed >> load_all_emr_sites  >> load_linelist_adverse_events >> load_linelist_appointments >> load_linelist_covid
Hi @nthusi-codes all the tasks or on one line here I dont think it applies

2023-11-24 06:23 UTC, nthusi-codes commented on production/dags/reporting_aggregates_tables_etl_dag.py
> +load_aggregate_txcurr >> load_aggregate_tx_new_hts_cascade  >> load_aggregate_vl_outcome_and_uptake >> load_aggregate_otz_eligibility_and_enrollments >> load_aggregate_otz_outcome >> load_aggregate_o
Seems like I missed that

2023-11-24 06:23 UTC, nthusi-codes approved these changes

2023-11-24 06:28 UTC, merged